language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode # JRuby in 1.9 mode

gemfile:
  - gemfiles/rspec2_14.gemfile
  - gemfiles/rspec3_0.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rspec3_0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rspec3_0.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rspec3_0.gemfile